//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashcards.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flashcards.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string Res_Bad {
            get {
                return ResourceManager.GetString("Res_Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards count.
        /// </summary>
        public static string Res_CardsCount {
            get {
                return ResourceManager.GetString("Res_CardsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Res_Colors {
            get {
                return ResourceManager.GetString("Res_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue quiz.
        /// </summary>
        public static string Res_ContinueQuiz {
            get {
                return ResourceManager.GetString("Res_ContinueQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string Res_DarkMode {
            get {
                return ResourceManager.GetString("Res_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Res_Data {
            get {
                return ResourceManager.GetString("Res_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Res_Details {
            get {
                return ResourceManager.GetString("Res_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End this quiz?.
        /// </summary>
        public static string Res_EndThisQuiz {
            get {
                return ResourceManager.GetString("Res_EndThisQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from quiz.
        /// </summary>
        public static string Res_ExcludeFromQuiz {
            get {
                return ResourceManager.GetString("Res_ExcludeFromQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Res_Export {
            get {
                return ResourceManager.GetString("Res_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Res_Good {
            get {
                return ResourceManager.GetString("Res_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Res_Import {
            get {
                return ResourceManager.GetString("Res_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Res_Language {
            get {
                return ResourceManager.GetString("Res_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string Res_Learn {
            get {
                return ResourceManager.GetString("Res_Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned.
        /// </summary>
        public static string Res_Learned {
            get {
                return ResourceManager.GetString("Res_Learned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn options.
        /// </summary>
        public static string Res_LearnOptions {
            get {
                return ResourceManager.GetString("Res_LearnOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashcards - Main page.
        /// </summary>
        public static string Res_MainPage {
            get {
                return ResourceManager.GetString("Res_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Res_Next {
            get {
                return ResourceManager.GetString("Res_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Res_No {
            get {
                return ResourceManager.GetString("Res_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Res_Previous {
            get {
                return ResourceManager.GetString("Res_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string Res_Quiz {
            get {
                return ResourceManager.GetString("Res_Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz options.
        /// </summary>
        public static string Res_QuizOptions {
            get {
                return ResourceManager.GetString("Res_QuizOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore defaults.
        /// </summary>
        public static string Res_RestoreDefaults {
            get {
                return ResourceManager.GetString("Res_RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete your courses with progress data and restore the app&apos;s default settings?.
        /// </summary>
        public static string Res_RestoreDefaultsMessage {
            get {
                return ResourceManager.GetString("Res_RestoreDefaultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select course.
        /// </summary>
        public static string Res_SelectCourse {
            get {
                return ResourceManager.GetString("Res_SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Res_Settings {
            get {
                return ResourceManager.GetString("Res_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only learned.
        /// </summary>
        public static string Res_UseOnlyLearned {
            get {
                return ResourceManager.GetString("Res_UseOnlyLearned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Res_Yes {
            get {
                return ResourceManager.GetString("Res_Yes", resourceCulture);
            }
        }
    }
}
